apiVersion: v1
kind: Service
metadata:
  name: my-postgres-local-nodeport
spec:
  type: NodePort
  selector:
    app: mypostgres
    replicationRole: primary
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30008
